set nocompatible

let $RC = "$HOME/.vim/vimrc"

set nowrap
set scrolloff=3

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

set bs=indent,eol,start

set foldmethod=marker

set autowrite

set undofile
set undodir="$HOME/.vim/undo"

set autoindent
set nosmartindent
set nocindent

set nohls
set incsearch

set wildmenu

set nrformats=bin,hex,alpha

set nu rnu

set showcmd

set timeout
set ttimeout
set timeoutlen=1000
set ttimeoutlen=100

set ruler

filetype indent plugin on

inoremap {<CR> {<CR>}<Esc>O
nnoremap UT :MundoShow<CR>

call plug#begin('~/.vim/plugged')
Plug 'cormacrelf/vim-colors-github'               " github colors
Plug 'sonph/onehalf', {'rtp': 'vim/'}             " one half colors
Plug 'tikhomirov/vim-glsl'
Plug 'crusoexia/vim-monokai'
Plug 'itchyny/landscape.vim'
Plug 'simnalamburt/vim-mundo'
call plug#end()

if has('termguicolors')
    set termguicolors

    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif

augroup filetype
    au! BufRead,BufNewFile *.ll     set filetype=llvm
augroup END

" stolen from https://shuheikagawa.com/blog/2020/02/14/switching-colorschemes-of-vim-and-alacritty/
let colorpath = expand('~/.vim/curcolor.vim')
if filereadable(colorpath)
    exec 'source' colorpath
endif

cnoreabbrev sorc so $RC
cnoreabbrev W w
cnoreabbrev www w!!sudo tee <C-R><C-R>% > /dev/null
cnoreabbrev mkss mks!

