#!/usr/bin/env bash
# killing {{{1
killall -q sxhkd polybar dunst picom
# sxhkd and bspwm {{{1
sxhkd &
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
# bspwm config {{{1
bspc config border_width         5
bspc config window_gap           5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
# colors {{{
bspc config normal_border_color   "#222222"
bspc config active_border_color   "#333333"
bspc config focused_border_color  "#777777"
bspc config presel_feedback_color "#aaaaaa"
# }}}
# padding {{{
bspc config top_padding 5
bspc config right_padding 5
bspc config bottom_padding 5
bspc config left_padding 5
# }}}
# bspwm rules {{{1
bspc rule -a Firefox desktop='^1'
# startup essentials {{{1
# use left pointer cursor instead of 'X' cursor
xsetroot -cursor_name left_ptr

feh --bg-scale --no-fehbg ~/Firefox_wallpaper.png
polybar main &
dunst &
picom \
    --shadow-radius=10 \
    --fade-in-step=0.1 \
    --fade-out-step=0.08 \
    --fade-delta=10 \
    --shadow \
    --fading &
# startup apps {{{1
firefox -p stuff &
firefox -p lsotnnirhcdfkb &
# disown {{{1
disown -r
